apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api
  namespace: saas-lab
  labels:
    app: internal-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-api
  template:
    metadata:
      labels:
        app: internal-api
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:1.0
        args: ["-text=internal-ok", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: internal-api
  namespace: saas-lab
spec:
  selector:
    app: internal-api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-worker
  namespace: saas-lab
  labels:
    app: payment-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-worker
  template:
    metadata:
      labels:
        app: payment-worker
    spec:
      containers:
      - name: curl
        image: curlimages/curl:8.7.1
        command: ["sleep", "infinity"]
