apiVersion: v1
kind: Namespace
metadata:
  name: storefront
  labels:
    purpose: ztbc-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: orders
  labels:
    purpose: ztbc-lab
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    purpose: ztbc-lab
