apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-api
  namespace: customer
  labels:
    app: profile-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-api
  template:
    metadata:
      labels:
        app: profile-api
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:1.0
        args: ["-text=team-profile-api", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: profile-api
  namespace: customer
spec:
  selector:
    app: profile-api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal
  namespace: customer
  labels:
    app: customer-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-portal
  template:
    metadata:
      labels:
        app: customer-portal
    spec:
      containers:
      - name: curl
        image: curlimages/curl:8.7.1
        command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: payments
  labels:
    app: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:1.0
        args: ["-text=team-payments-api", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: payments
spec:
  selector:
    app: payments-api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
  namespace: payments
  labels:
    app: payments-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      containers:
      - name: curl
        image: curlimages/curl:8.7.1
        command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-auth-api
  namespace: shared
  labels:
    app: shared-auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-auth-api
  template:
    metadata:
      labels:
        app: shared-auth-api
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:1.0
        args: ["-text=shared-auth-api", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shared-auth-api
  namespace: shared
spec:
  selector:
    app: shared-auth-api
  ports:
  - port: 8080
    targetPort: 8080
