apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
  namespace: selector-lab
  labels:
    app: inventory-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:1.0
        args: ["-text=inventory-ok", "-listen=:8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-api
  namespace: selector-lab
spec:
  selector:
    app: inventory-api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: selector-lab
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: curl
        image: curlimages/curl:8.7.1
        command: ["sleep", "infinity"]
